export const categories = {
  MOTIVATION:         { label: 'Motivation',          emoji: '🚀' },
  SUCCESS:            { label: 'Success',             emoji: '🏆' },
  TECH:               { label: 'Tech',                emoji: '💻' },
  CRITICAL_THINKING:  { label: 'Critical Thinking',   emoji: '🧠' },
  HINDI:              { label: 'हिंदी विचार',         emoji: '🇮🇳' },
  URDU:               { label: 'اردو اقوال',          emoji: '🌙' },
  LOVE:               { label: 'Love',                emoji: '💕' },
  WISDOM:             { label: 'Wisdom',              emoji: '🦉' },
  LIFE:               { label: 'Life',                emoji: '🌟' },
  FUNNY:              { label: 'Funny',               emoji: '😂' },
  LEADERSHIP:         { label: 'Leadership',          emoji: '👑' },
  EDUCATION:          { label: 'Education',           emoji: '📚' },
  SPIRITUALITY:       { label: 'Spirituality',        emoji: '🙏' },
  NATURE:             { label: 'Nature',              emoji: '🌿' },
  LIKED:              { label: 'Liked Quotes',        emoji: '❤️' }
}

export const gradients = {
  MOTIVATION:         ['#667EEA', '#764BA2'],
  SUCCESS:            ['#F093FB', '#F5576C'],
  TECH:               ['#4FACFE', '#00F2FE'],
  CRITICAL_THINKING:  ['#43E97B', '#38F9D7'],
  HINDI:              ['#FF9933', '#138808'],
  URDU:               ['#2B6B4F', '#1A4731'],
  LOVE:               ['#FF6B6B', '#EE5A24'],
  WISDOM:             ['#8E44AD', '#2C3E50'],
  LIFE:               ['#00B4DB', '#0083B0'],
  FUNNY:              ['#F2994A', '#F2C94C'],
  LEADERSHIP:         ['#F7971E', '#FFD200'],
  EDUCATION:          ['#11998E', '#38EF7D'],
  SPIRITUALITY:       ['#8360C3', '#2EBF91'],
  NATURE:             ['#2D6A4F', '#52B788'],
  LIKED:              ['#E91E63', '#9C27B0']
}

export const currentYear = new Date().getFullYear()

export const allQuotes = [
  // ── MOTIVATION (12) ──
  { text: 'The only way to do great work is to love what you do. If you haven\'t found it yet, keep looking. Don\'t settle. As with all matters of the heart, you\'ll know when you find it.', author: 'Steve Jobs', category: 'MOTIVATION' },
  { text: 'Believe you can and you\'re halfway there. The moment you doubt whether you can fly, you cease forever to be able to do it. Self-belief is the foundation of all achievement.', author: 'Theodore Roosevelt', category: 'MOTIVATION' },
  { text: 'It does not matter how slowly you go as long as you do not stop. Progress is progress, no matter how small. Every step forward, no matter how tiny, brings you closer to your destination.', author: 'Confucius', category: 'MOTIVATION' },
  { text: 'Your time is limited, so don\'t waste it living someone else\'s life. Don\'t be trapped by dogma — which is living with the results of other people\'s thinking. Don\'t let the noise of others\' opinions drown out your own inner voice.', author: 'Steve Jobs', category: 'MOTIVATION' },
  { text: 'Everything you\'ve ever wanted is on the other side of fear. Fear is nothing more than a mental barrier. Break through it and you will discover a world of endless possibilities waiting for you to seize them.', author: 'George Addair', category: 'MOTIVATION' },
  { text: 'The future belongs to those who believe in the beauty of their dreams. Never stop dreaming because dreams are the seeds of reality. Water them with hard work and watch them bloom into something extraordinary.', author: 'Eleanor Roosevelt', category: 'MOTIVATION' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts. The road to success is paved with setbacks, but those who keep moving forward despite the odds are the ones who ultimately triumph.', author: 'Winston Churchill', category: 'MOTIVATION' },
  { text: 'The only limit to our realization of tomorrow will be our doubts of today. Let us move forward with strong and active faith. The mind is everything; what you think, you become.', author: 'Franklin D. Roosevelt', category: 'MOTIVATION' },
  { text: 'Don\'t watch the clock; do what it does. Keep going. Time waits for no one, and the best way to make the most of it is to stay in motion, constantly pushing forward toward your goals.', author: 'Sam Levenson', category: 'MOTIVATION' },
  { text: 'Act as if what you do makes a difference. It does. Every action you take, no matter how small, creates a ripple effect that extends far beyond what you can see. You are more powerful than you realize.', author: 'William James', category: 'MOTIVATION' },
  { text: 'When you feel like quitting, remember why you started. Every successful person has a story of persistence. The difference between winners and quitters is that winners never gave up when things got hard.', author: 'Sohel Khan', category: 'MOTIVATION' },
  { text: 'Hard times create strong people. Strong people create good times. Good times create weak people. And weak people create hard times. Stay strong through every season of life and break the cycle of mediocrity.', author: 'Sohel Khan', category: 'MOTIVATION' },
  // ── SUCCESS (12) ──
  { text: 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. True success comes from within, not from external validation or material wealth.', author: 'Albert Schweitzer', category: 'SUCCESS' },
  { text: 'Don\'t be afraid to give up the good to go for the great. Many people settle for mediocrity because greatness requires sacrifice. The comfort zone is a beautiful place, but nothing ever grows there.', author: 'John D. Rockefeller', category: 'SUCCESS' },
  { text: 'The secret of success is to do the common things uncommonly well. Excellence is not about doing extraordinary things; it is about doing ordinary things with extraordinary dedication and attention to detail.', author: 'John D. Rockefeller Jr.', category: 'SUCCESS' },
  { text: 'Success usually comes to those who are too busy to be looking for it. Focus on the work, pour your heart into it, and success will follow naturally. The more you chase success, the more it will elude you.', author: 'Henry David Thoreau', category: 'SUCCESS' },
  { text: 'Opportunities don\'t happen. You create them. Stop waiting for the perfect moment. Take the moment and make it perfect. The world belongs to those who take initiative and create their own path.', author: 'Chris Grosser', category: 'SUCCESS' },
  { text: 'The only place where success comes before work is in the dictionary. There are no shortcuts to any place worth going. Hard work, discipline, and consistency are the only proven paths to lasting success.', author: 'Vidal Sassoon', category: 'SUCCESS' },
  { text: 'Success is walking from failure to failure with no loss of enthusiasm. Every setback is a setup for a comeback. The most successful people in history failed more times than most people ever try.', author: 'Winston Churchill', category: 'SUCCESS' },
  { text: 'I find that the harder I work, the more luck I seem to have. What people call luck is actually the intersection of preparation and opportunity. Put in the work and watch how lucky you become.', author: 'Thomas Jefferson', category: 'SUCCESS' },
  { text: 'Try not to become a man of success. Rather become a man of value. When you focus on adding value to the world and to others, success becomes a natural byproduct of your contribution.', author: 'Albert Einstein', category: 'SUCCESS' },
  { text: 'Success is not in what you have, but who you are. True wealth is measured not by the size of your bank account, but by the size of your heart and the depth of your character.', author: 'Bo Bennett', category: 'SUCCESS' },
  { text: 'Success is the sum of small efforts repeated day in and day out. Greatness is not achieved in a single leap but through consistent, deliberate practice over time. Show up every single day.', author: 'Robert Collier', category: 'SUCCESS' },
  { text: 'The difference between who you are and who you want to be is what you do. Dreams without action remain dreams. Action without dreams is wasted energy. Combine both and nothing can stop you.', author: 'Sohel Khan', category: 'SUCCESS' },
  // ── TECH (12) ──
  { text: 'The technology you use impresses no one. The experience you create with it is everything. The best technology is invisible — it seamlessly integrates into people\'s lives and makes things better without being noticed.', author: 'Sean Geraty', category: 'TECH' },
  { text: 'It\'s not that we use technology, we live technology. Technology has become so deeply intertwined with our daily existence that the boundary between human and machine continues to blur.', author: 'Godfrey Reggio', category: 'TECH' },
  { text: 'Any sufficiently advanced technology is indistinguishable from magic. What seems impossible today will be ordinary tomorrow. The pace of innovation keeps accelerating, turning science fiction into science fact.', author: 'Arthur C. Clarke', category: 'TECH' },
  { text: 'First we shape our tools, then our tools shape us. The relationship between humans and technology is reciprocal. We create technology, and in turn, technology reshapes how we think, communicate, and live.', author: 'Marshall McLuhan', category: 'TECH' },
  { text: 'Code is like humor. When you have to explain it, it\'s bad. Good code should be self-documenting, readable, and elegant. The best programmers write code that other humans can understand, not just machines.', author: 'Cory House', category: 'TECH' },
  { text: 'The computer was born to solve problems that did not exist before. Every technological breakthrough creates new challenges while solving old ones. Progress is a never-ending cycle of problem and solution.', author: 'Bill Gates', category: 'TECH' },
  { text: 'The advance of technology is based on making it fit in so that you don\'t really even notice it, so it\'s part of everyday life. The ultimate goal of any technology should be to enhance human capability effortlessly.', author: 'Bill Gates', category: 'TECH' },
  { text: 'Technology is best when it brings people together. The true measure of any technological advancement is not its complexity or speed, but its ability to connect humans and strengthen relationships.', author: 'Matt Mullenweg', category: 'TECH' },
  { text: 'Innovation distinguishes between a leader and a follower. Leaders don\'t wait for change to happen — they make it happen. They see possibilities where others see obstacles and dare to tread where others fear.', author: 'Steve Jobs', category: 'TECH' },
  { text: 'The science of today is the technology of tomorrow. Every line of research, every experiment, every discovery builds the foundation for the innovations that will define our future.', author: 'Edward Teller', category: 'TECH' },
  { text: 'Technology is a useful servant but a dangerous master. We must never let technology control us. Instead, we should harness it as a tool to amplify human creativity, compassion, and connection.', author: 'Christian Lous Lange', category: 'TECH' },
  { text: 'The greatest danger in times of turbulence is not the turbulence; it is to act with yesterday\'s logic. In a world of exponential change, adaptability is the single most important skill.', author: 'Peter Drucker', category: 'TECH' },
  // ── CRITICAL THINKING (12) ──
  { text: 'The unexamined life is not worth living. Self-reflection is the cornerstone of wisdom. Without questioning our own beliefs, actions, and motivations, we drift through life on autopilot.', author: 'Socrates', category: 'CRITICAL_THINKING' },
  { text: 'It is the mark of an educated mind to be able to entertain a thought without accepting it. True intelligence means being able to consider opposing viewpoints without immediate judgment.', author: 'Aristotle', category: 'CRITICAL_THINKING' },
  { text: 'We cannot solve our problems with the same thinking we used when we created them. To overcome challenges, we must elevate our consciousness and approach problems from entirely new perspectives.', author: 'Albert Einstein', category: 'CRITICAL_THINKING' },
  { text: 'Question everything. Learn something. Answer nothing. The wisest people are not those who have all the answers, but those who know how to ask the right questions.', author: 'Euripides', category: 'CRITICAL_THINKING' },
  { text: 'Thinking is the hardest work there is, which is probably the reason so few engage in it. Most people would rather accept comfortable lies than wrestle with uncomfortable truths.', author: 'Henry Ford', category: 'CRITICAL_THINKING' },
  { text: 'Wise men speak because they have something to say; fools because they have to say something. Before you speak, ask yourself: Is it true? Is it necessary? Is it kind? Is it adding value?', author: 'Plato', category: 'CRITICAL_THINKING' },
  { text: 'The important thing is not to stop questioning. Curiosity has its own reason for existing. Never lose a holy curiosity. Question everything you see, hear, and read.', author: 'Albert Einstein', category: 'CRITICAL_THINKING' },
  { text: 'To know what you know and what you do not know, that is true knowledge. Intellectual humility is recognizing the limits of your understanding and being open to learning from anyone, anywhere.', author: 'Confucius', category: 'CRITICAL_THINKING' },
  { text: 'An investment in knowledge pays the best interest. Every book you read, every skill you acquire, every lesson you learn compounds over time into a wealth that no market crash can take away.', author: 'Benjamin Franklin', category: 'CRITICAL_THINKING' },
  { text: 'Doubt is not a pleasant condition, but certainty is absurd. Absolute certainty is the enemy of growth. Embrace uncertainty and let it drive you to explore, discover, and understand more deeply.', author: 'Voltaire', category: 'CRITICAL_THINKING' },
  { text: 'The first principle is that you must not fool yourself — and you are the easiest person to fool. Be ruthless in examining your own biases and assumptions. Intellectual honesty starts from within.', author: 'Richard Feynman', category: 'CRITICAL_THINKING' },
  { text: 'Your assumptions are your windows on the world. Scrub them off every once in a while, or the light won\'t come in. Challenge your beliefs regularly to see the world as it truly is.', author: 'Isaac Asimov', category: 'CRITICAL_THINKING' },
  // ── HINDI (50) ──
  { text: 'अपने लक्ष्य को इतना बड़ा बनाओ कि रास्ते छोटे लगें। जब तुम्हारा सपना बड़ा होगा, तो हर चुनौती छोटी लगने लगेगी और तुम्हारा आत्मविश्वास अपने आप बढ़ता जाएगा।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जिंदगी में दो चीजें कभी मत छोड़ो — एक उम्मीद और दूसरा हौसला। ये दोनों ही तुम्हें हर मुश्किल से लड़ने की ताकत देते हैं और अंधेरे में भी रोशनी दिखाते हैं।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'कामयाबी उन्हीं को मिलती है जो अपनी गलतियों से सीखते हैं। गलतियां असफलता नहीं, सबक हैं। हर गलती तुम्हें एक कदम और मजबूत बनाती है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'मंजिल उन्हीं को मिलती है जिनके सपनों में जान होती है। पंखों से कुछ नहीं होता, हौसलों से उड़ान होती है। बस अपने सपने पर यकीन रखो और उड़ान भरो।', author: 'डॉ. ए.पी.जे. अब्दुल कलाम', category: 'HINDI' },
  { text: 'सपने वो नहीं जो हम सोते वक्त देखते हैं, सपने वो हैं जो हमें सोने नहीं देते। अगर तुम्हारा लक्ष्य तुम्हें रातों की नींद नहीं लेने देता, तो समझ लो तुम सही रास्ते पर हो।', author: 'डॉ. ए.पी.जे. अब्दुल कलाम', category: 'HINDI' },
  { text: 'जिंदगी एक खेल है, इसे खेलना सीखो। हार और जीत दोनों को समान भाव से स्वीकार करो। जो खिलाड़ी हार से नहीं डरता, वही असली विजेता होता है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'सफलता का कोई शॉर्टकट नहीं होता, मेहनत ही एकमात्र रास्ता है। जो लोग शॉर्टकट ढूंढते हैं, वे अक्सर लंबा रास्ता तय करते हैं। सीधा रास्ता ही सबसे छोटा रास्ता है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'उठो, जागो और तब तक मत रुको जब तक लक्ष्य प्राप्त न हो जाए। जीवन एक अवसर है, इसे व्यर्थ मत जाने दो। हर सुबह एक नया मौका लेकर आती है।', author: 'स्वामी विवेकानंद', category: 'HINDI' },
  { text: 'कठिनाइयों से भागो मत, उनका सामना करो। जो तूफानों से लड़ता है, वही समंदर पार करता है। हर मुश्किल तुम्हें कल के लिए और मजबूत बनाती है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जो खुद पर विश्वास करते हैं, वही दुनिया जीतते हैं। आत्मविश्वास वो हथियार है जिससे तुम कोई भी जंग जीत सकते हो। खुद पर भरोसा रखो, दुनिया तुम पर भरोसा करेगी।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जीवन में जो कुछ भी बड़ा हासिल होता है, वो पहले सपने में आता है। हर बड़ी उपलब्धि की शुरुआत एक छोटे से विचार से होती है। अपने विचारों को कभी कम मत आंको।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'अकेले चलो, अगर कोई साथ नहीं देता। रास्ता खुद बन जाएगा। दुनिया उन्हीं का साथ देती है जो खुद पर भरोसा करते हैं। अकेले चलना सीखो, फिर देखो कितने लोग तुम्हारे पीछे चलते हैं।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'मेहनत इतनी खामोशी से करो कि सफलता शोर मचा दे। जब तुम अपने काम में डूब जाते हो, तो दुनिया खुद तुम्हारी तारीफ करने लगती है। कर्म बोलता है, शब्द नहीं।', author: 'डॉ. ए.पी.जे. अब्दुल कलाम', category: 'HINDI' },
  { text: 'जो हम सोचते हैं वो हम बन जाते हैं। तुम्हारी सोच ही तुम्हारी पहचान है। अगर तुम बड़ा सोचोगे, तो एक दिन बड़े बन जाओगे। कोई भी तुम्हें रोक नहीं सकता।', author: 'महात्मा गांधी', category: 'HINDI' },
  { text: 'मन के हारे हार है, मन के जीते जीत। जीवन की सबसे बड़ी जंग खुद से होती है। जो खुद को जीत लेता है, उसे दुनिया कोई नहीं हरा सकता।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'हिम्मत वह नहीं जो गिरने से बचाए, हिम्मत वो है जो गिरने के बाद उठना सिखाए। हर कोई गिरता है, लेकिन सिर्फ बहादुर लोग ही बार-बार उठते हैं।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जो वक्त का इंतजार करते हैं, वक्त उनका नहीं होता। सही समय का इंतजार मत करो — जो समय तुम्हारे पास है, उसे ही सही बना लो। कल कभी नहीं आता।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'बुरा जो देखन मैं चला, बुरा न मिलिया कोय। जो मन खोजा आपना, तो मुझसे बुरा न कोय। दुनिया में बुराई ढूंढने से पहले खुद के अंदर झांको।', author: 'संत कबीर दास', category: 'HINDI' },
  { text: 'दुख में सुमिरन सब करें, सुख में करे न कोय। जो सुख में सुमिरन करे, तो दुख काहे को होय। ईश्वर को सिर्फ मुश्किल वक्त में नहीं, हर वक्त याद करो।', author: 'संत कबीर दास', category: 'HINDI' },
  { text: 'जीवन एक उपहार है, इसे स्वीकार करो और हर पल को जियो। कल की चिंता और कल के पछतावे में अपना आज मत खराब करो। आज में जीना सीखो।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'कोशिश करने वालों की कभी हार नहीं होती। चाहे कितनी भी बड़ी बाधा आए, हार नहीं माननी चाहिए। लहरों से डरकर नौका पार नहीं होती।', author: 'हरिवंश राय बच्चन', category: 'HINDI' },
  { text: 'हर सुबह एक नई उम्मीद लेकर आती है और हर रात एक नया सबक सिखाकर जाती है। जीवन का हर दिन एक नई सीख है, बस आंखें खोलकर देखने की जरूरत है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'सपने बड़े देखो, मेहनत उतनी ही करो। छोटे सपने तुम्हें कभी बड़ा इंसान नहीं बना सकते। आसमान की ऊंचाइयों को छूने के लिए उतनी ही ऊंची सोच रखनी होगी।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'कर्म करो, फल की चिंता मत करो। तुम्हारा काम है प्रयास करना, परिणाम की जिम्मेदारी ईश्वर पर छोड़ दो। बस अपना शत-प्रतिशत दो और बाकी समय पर छोड़ दो।', author: 'भगवद् गीता', category: 'HINDI' },
  { text: 'एक छोटी सी सकारात्मक सोच आपकी पूरी जिंदगी बदल सकती है। नकारात्मकता एक जहर है जो धीरे-धीरे तुम्हें अंदर से खोखला कर देती है। सकारात्मक सोचो, सकारात्मक रहो।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जो बीत गया सो बीत गया, अब आगे बढ़ो। अतीत की गलतियों में उलझकर मत रहो। उनसे सीखो और आगे का रास्ता तय करो। बीते हुए कल को बदला नहीं जा सकता।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'बिना संघर्ष के कुछ भी हासिल नहीं होता। सोना भी आग में तपकर ही कुंदन बनता है। संघर्ष ही जीवन का असली सौंदर्य है, इससे भागो मत, इसे गले लगाओ।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'हार मत मानो, क्योंकि असंभव सिर्फ एक राय है, सच्चाई नहीं। जिसे दुनिया नामुमकिन कहती है, वह किसी के लिए मुमकिन होता है। बस वह कोई तुम बनो।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'समय बर्बाद मत करो, क्योंकि यही जिंदगी है। जो पल एक बार चला जाता है, वो कभी वापस नहीं आता। हर सेकंड कीमती है। इसका सही उपयोग करो।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'पहले खुद को बदलो, फिर दुनिया बदलेगी। दुनिया को बदलने की चाहत रखने से पहले खुद को बदलो। जब तुम बदलोगे, तो तुम्हारी दुनिया अपने आप बदल जाएगी।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'दूसरों की तारीफ करना सीखो, यह सबसे बड़ी नेकी है। किसी की तारीफ करने से तुम्हारा कुछ नहीं जाता, बल्कि रिश्ते मजबूत होते हैं और दिल जीते जाते हैं।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जीवन में लक्ष्य होना जरूरी है, वरना जीवन दिशाहीन हो जाता है। बिना मंजिल के सफर का कोई मतलब नहीं। एक स्पष्ट लक्ष्य तय करो और उस पर डटे रहो।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'खुद को पहचानो, यही सबसे बड़ी सफलता है। जब तक तुम खुद को नहीं जानते, तब तक तुम दुनिया को क्या जानोगे। खुद की पहचान ही असली ज्ञान है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जो दूसरों के लिए जीता है, वही सच्चा इंसान है। सिर्फ अपने लिए जीना तो जानवर भी जानते हैं। इंसान वही है जो दूसरों की भलाई में अपनी खुशी ढूंढे।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'मंजिल पाने का जुनून हो तो रास्ते खुद बन जाते हैं। जब इरादे मजबूत हों, तो राहें अपने आप निकल आती हैं। बस चलने का जुनून चाहिए, रास्ता मिल ही जाएगा।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'ज्ञान ही शक्ति है। यह दुनिया का सबसे बड़ा हथियार है जिसे कोई चुरा नहीं सकता। जितना ज्यादा ज्ञान बांटोगे, उतना ही बढ़ेगा।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'सब्र का फल मीठा होता है। जल्दबाजी में किए गए काम अक्सर पछतावे का कारण बनते हैं। धैर्य रखो, सही समय का इंतजार करो, सफलता जरूर मिलेगी।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'इंसानियत ही सबसे बड़ा धर्म है। जाति, धर्म, रंग, भाषा से ऊपर उठकर सबसे पहले इंसान बनो। इंसानियत से बड़ा कोई मजहब नहीं।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'परिश्रम का कोई तोड़ नहीं है। भाग्य भी उन्हीं का साथ देता है जो मेहनत करते हैं। भाग्य के भरोसे बैठे रहने वाले कभी सफल नहीं होते।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'स्वास्थ्य ही सबसे बड़ा धन है। तन सेहतमंद होगा तो मन भी स्वस्थ रहेगा। धन-दौलत सब बाद में, पहले अपनी सेहत का ख्याल रखो।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जहां प्रेम है, वहां ईश्वर है। प्रेम ही ईश्वर का सबसे बड़ा रूप है। जहां सच्चा प्रेम होता है, वहां किसी मंदिर या मस्जिद की जरूरत नहीं होती।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'अनुभव सबसे बड़ा गुरु है। किताबों से ज्यादा जिंदगी सिखाती है। हर ठोकर एक सबक है, हर हार एक अनुभव। इनसे सीखो और आगे बढ़ो।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'दूसरों की मदद करने से बड़ा कोई पुण्य नहीं। जब तुम किसी जरूरतमंद की मदद करते हो, तो ईश्वर खुद तुम्हारी मदद करता है। सेवा ही सबसे बड़ा धर्म है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जिंदगी खूबसूरत है, बस नजरिया बदलने की देर है। सब कुछ तुम्हारे पास है, बस देखने का तरीका बदलो। कमियों की जगह खूबियां गिनो, जिंदगी खुद-ब-खुद खूबसूरत लगने लगेगी।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'पहला कदम सबसे मुश्किल होता है, लेकिन एक बार चल पड़े तो मंजिल खुद-ब-खुद करीब आने लगती है। शुरुआत करो, बाकी सब अपने आप होता जाएगा।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जीतने वाले अलग चीजें नहीं करते, वे चीजों को अलग तरीके से करते हैं। सफलता का राज किसी खास योग्यता में नहीं, बल्कि सोचने के अनोखे तरीके में छिपा है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'हर बड़ी सफलता के पीछे अनगिनत छोटी-छोटी असफलताएं छिपी होती हैं। जो चेहरे की मुस्कान देखते हैं, वो आंखों के आंसू नहीं देखते।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'ईमानदारी सबसे महंगी चीज है, लेकिन हर कोई इसकी कीमत नहीं चुका सकता। ईमानदार रहना मुश्किल जरूर है, लेकिन असंभव नहीं।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'अच्छे दोस्त वो नहीं जो हर वक्त साथ रहते हैं, बल्कि वो हैं जो मुश्किल वक्त में भी साथ खड़े रहते हैं। सच्ची दोस्ती परख मुश्किलों में होती है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जब तक तुम प्रयास नहीं करते, तब तक तुम्हें पता भी नहीं चलेगा कि तुम क्या कर सकते हो। अपनी सीमाओं को तोड़ो और अपनी असली ताकत पहचानो।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'दुनिया उनकी इज्जत करती है जो खुद की इज्जत करते हैं। आत्मसम्मान से बड़ी कोई पूंजी नहीं। इसे कभी मत खोना।', author: 'Sohel Khan', category: 'HINDI' },
  // ── URDU (30) ──
  { text: 'خدا اس کی مدد کرتا ہے جو خود اپنی مدد کرتا ہے۔ جب تم خود کوشش کرتے ہو، تو خدا بھی تمہارے لیے راستے آسان کر دیتا ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'محنت کا کوئی متبادل نہیں ہے۔ چاہے دنیا کی ساری دولت بھی کیوں نہ مل جائے، محنت کے بغیر کامیابی کا کوئی شارٹ کٹ نہیں ہوتا۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'جہاں چاہ وہاں راہ۔ جب ارادہ پختہ ہو، تو راستے خود بخود بن جاتے ہیں۔ بس چلنے کا حوصلہ چاہیے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'اپنے خوابوں کو اتنا بڑا بناؤ کہ راستے چھوٹے لگیں۔ بڑے خواب دیکھو، پھر انہیں حقیقت بنانے کے لیے دن رات محنت کرو۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'زندگی میں دو چیزیں کبھی مت چھوڑو — ایک امید اور دوسرا حوصلہ۔ یہ دونوں ہی تمہیں ہر مشکل سے لڑنے کی طاقت دیتے ہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'کامیابی انہیں کو ملتی ہے جو اپنی غلطیوں سے سیکھتے ہیں۔ غلطیاں ناکامی نہیں، سبق ہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'خواب وہ نہیں جو ہم سوتے وقت دیکھتے ہیں، خواب وہ ہیں جو ہمیں سونے نہیں دیتے۔', author: 'ڈاکٹر اے پی جے عبدالکلام', category: 'URDU' },
  { text: 'زندگی ایک کھیل ہے، اسے کھیلنا سیکھو۔ ہار یا جیت قسمت کی بات ہے، لیکن کوشش کرنا تمہارے ہاتھ میں ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'اٹھو، جاگو اور تب تک مت رکو جب تک منزل حاصل نہ ہو جائے۔ زندگی ایک موقع ہے، اسے ضائع مت کرو۔', author: 'سوامی ویویکانند', category: 'URDU' },
  { text: 'مشکلات سے بھاگو مت، ان کا سامنا کرو۔ جو طوفانوں سے لڑتا ہے، وہی سمندر پار کرتا ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'جو خود پر یقین رکھتے ہیں، وہی دنیا جیتتے ہیں۔ خود اعتمادی وہ ہتھیار ہے جس سے تم کوئی بھی جنگ جیت سکتے ہو۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'خود پر یقین رکھنے والے لوگ ہی تاریخ بناتے ہیں۔ جو اپنی صلاحیتوں پر شک کرتے ہیں، وہ کبھی بڑے نہیں بن سکتے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'خوش رہنا سب سے بڑی کامیابی ہے۔ دولت اور شہرت سے زیادہ اہم دل کا سکون ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'وقت کسی کے لیے نہیں رکتا، اس لیے ابھی شروع کرو۔ کل کا انتظار کرنے والے کبھی کچھ نہیں کر پاتے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'عشق نے غالبؔ نکما کر دیا، ورنہ ہم بھی آدمی تھے کام کے۔ محبت انسان کو بدل دیتی ہے۔', author: 'مرزا غالب', category: 'URDU' },
  { text: 'ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے۔ بہت نکلے مرے ارمان لیکن پھر بھی کم نکلے۔', author: 'مرزا غالب', category: 'URDU' },
  { text: 'خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے، خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے۔', author: 'علامہ اقبال', category: 'URDU' },
  { text: 'تعلیم سب سے طاقتور ہتھیار ہے جس سے آپ دنیا بدل سکتے ہیں۔ علم سے بڑھ کر کوئی طاقت نہیں۔', author: 'نیلسن منڈیلا', category: 'URDU' },
  { text: 'محنت اتنی خاموشی سے کرو کہ کامیابی شور مچا دے۔', author: 'ڈاکٹر اے پی جے عبدالکلام', category: 'URDU' },
  { text: 'ہر صبح ایک نئی امید لے کر آتی ہے۔ ہر دن ایک نیا موقع ہے کچھ بہتر کرنے کا۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'جو شخص خود کو ہرا دیتا ہے، وہ دنیا کو ہرا سکتا ہے۔ سب سے بڑی جیت خود پر جیت ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'صبر کا پھل میٹھا ہوتا ہے۔ جلد بازی میں کیے گئے کام اکثر پچھتاوے کا سبب بنتے ہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'علم ہی طاقت ہے۔ یہ دنیا کا سب سے بڑا ہتھیار ہے جسے کوئی چرا نہیں سکتا۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'دنیا میں کچھ بھی ناممکن نہیں ہے۔ لفظ ناممکن صرف ایک رائے ہے، حقیقت نہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'اچھے اعمال کبھی رائیگاں نہیں جاتے۔ جو بھلائی تم کرتے ہو، وہ کسی نہ کسی صورت میں تمہارے پاس واپس آتی ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'زندگی چھوٹی ہے، اسے بڑے کاموں کے لیے استعمال کرو۔ چھوٹی سوچ چھوٹی زندگی دیتی ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'ہار تب نہیں ہوتی جب آپ گرتے ہیں، ہار تب ہوتی ہے جب آپ اٹھتے نہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'محبت انسان کو بدل دیتی ہے۔ جس سے محبت ہو جائے، وہی سب سے خوبصورت لگنے لگتا ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'دوست وہ نہیں جو ہر وقت ساتھ ہوں، دوست وہ ہیں جو مشکل وقت میں بھی ساتھ کھڑے رہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'سچ بولنے والے کو کبھی ڈرنے کی ضرورت نہیں ہوتی۔ سچ سب سے بڑی طاقت ہے۔', author: 'Sohel Khan', category: 'URDU' },
  // ── LOVE (12) ──
  { text: 'Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day, even when things get difficult and the world seems against you.', author: 'Sohel Khan', category: 'LOVE' },
  { text: 'The best thing to hold onto in life is each other. When everything else fades away — money, fame, possessions — love remains the only thing that truly matters.', author: 'Audrey Hepburn', category: 'LOVE' },
  { text: 'Where there is love there is life. Love is the spark that ignites the human spirit. Without love, existence is merely survival, not living.', author: 'Mahatma Gandhi', category: 'LOVE' },
  { text: 'Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope. True love is unstoppable.', author: 'Maya Angelou', category: 'LOVE' },
  { text: 'To love and be loved is to feel the sun from both sides. There is no greater warmth in this world than the warmth of mutual, unconditional love.', author: 'David Viscott', category: 'LOVE' },
  { text: 'Love is composed of a single soul inhabiting two bodies. When two people are truly in love, they become two halves of one complete whole.', author: 'Aristotle', category: 'LOVE' },
  { text: 'The greatest happiness of life is the conviction that we are loved — loved for ourselves, or rather, loved in spite of ourselves.', author: 'Victor Hugo', category: 'LOVE' },
  { text: 'Love all, trust a few, do wrong to none. Be generous with your heart, but wise with your trust. That is the secret to a life filled with meaningful relationships.', author: 'William Shakespeare', category: 'LOVE' },
  { text: 'A loving heart is the truest wisdom. Intelligence without compassion is dangerous. Knowledge without kindness is hollow. Love is the highest form of intelligence.', author: 'Charles Dickens', category: 'LOVE' },
  { text: 'In the end, the love you take is equal to the love you make. You receive from the universe exactly what you put into it. Give love and love will find you.', author: 'Paul McCartney', category: 'LOVE' },
  { text: 'Love is the only force capable of transforming an enemy into a friend. Hatred multiplies hatred, but love has the power to break the cycle and create peace where there was conflict.', author: 'Martin Luther King Jr.', category: 'LOVE' },
  { text: 'The best love is the kind that awakens the soul and makes us reach for more, that plants a fire in our hearts and brings peace to our minds.', author: 'Nicholas Sparks', category: 'LOVE' },
  // ── WISDOM (12) ──
  { text: 'The only true wisdom is in knowing you know nothing. The moment you think you know everything, you stop learning. Humility is the beginning of all wisdom.', author: 'Socrates', category: 'WISDOM' },
  { text: 'Knowledge speaks, but wisdom listens. Anyone can talk, but only the truly wise understand the value of silence and the power of truly hearing what others have to say.', author: 'Jimi Hendrix', category: 'WISDOM' },
  { text: 'Turn your wounds into wisdom. Every painful experience carries within it the seed of growth. The difference between suffering and wisdom is whether you learn from your pain.', author: 'Oprah Winfrey', category: 'WISDOM' },
  { text: 'The fool doth think he is wise, but the wise man knows himself to be a fool. Self-awareness is the first step toward genuine wisdom.', author: 'William Shakespeare', category: 'WISDOM' },
  { text: 'Wisdom begins in wonder. Curiosity is the engine of growth. The wisest people never lose their childlike sense of amazement at the world around them.', author: 'Socrates', category: 'WISDOM' },
  { text: 'By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.', author: 'Confucius', category: 'WISDOM' },
  { text: 'Honesty is the first chapter in the book of wisdom. Without truthfulness — first to yourself and then to others — all other knowledge is built on a shaky foundation.', author: 'Thomas Jefferson', category: 'WISDOM' },
  { text: 'It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it. Sometimes the wisest thing you can say is nothing at all.', author: 'Maurice Switzer', category: 'WISDOM' },
  { text: 'Silence is the sleep that nourishes wisdom. In the noise of the modern world, the ability to find quiet moments for reflection is a superpower.', author: 'Francis Bacon', category: 'WISDOM' },
  { text: 'Not everything that is faced can be changed, but nothing can be changed until it is faced. Wisdom is knowing what you can control and having the courage to act on it.', author: 'James Baldwin', category: 'WISDOM' },
  { text: 'The simple things are also the most extraordinary things, and only the wise can see them. Happiness is found not in grand gestures, but in everyday moments.', author: 'Paulo Coelho', category: 'WISDOM' },
  { text: 'Wisdom is not a product of schooling but of the lifelong attempt to acquire it. Formal education gives you knowledge, but life experience gives you wisdom.', author: 'Albert Einstein', category: 'WISDOM' },
  // ── LIFE (12) ──
  { text: 'Life is what happens when you\'re busy making other plans. While you are worrying about tomorrow, today is slipping away. Be present. Be here now.', author: 'John Lennon', category: 'LIFE' },
  { text: 'The purpose of our lives is to be happy. At the end of the day, all the achievements and possessions mean nothing if they don\'t contribute to your genuine happiness.', author: 'Dalai Lama', category: 'LIFE' },
  { text: 'In three words I can sum up everything I\'ve learned about life: it goes on. No matter what happens — joy or sorrow, victory or defeat — life continues. And so must you.', author: 'Robert Frost', category: 'LIFE' },
  { text: 'Life is really simple, but we insist on making it complicated. We add layers of worry, ego, and attachment to what is fundamentally a beautiful, simple existence.', author: 'Confucius', category: 'LIFE' },
  { text: 'The biggest adventure you can take is to live the life of your dreams. Don\'t settle for a life of quiet desperation. Have the courage to pursue what truly sets your soul on fire.', author: 'Oprah Winfrey', category: 'LIFE' },
  { text: 'Life is either a daring adventure or nothing at all. Security is mostly a superstition. Avoiding danger is no safer in the long run than outright exposure.', author: 'Helen Keller', category: 'LIFE' },
  { text: 'Life is 10% what happens to us and 90% how we react to it. You cannot control the events of life, but you can always control your response to them.', author: 'Charles R. Swindoll', category: 'LIFE' },
  { text: 'The good life is one inspired by love and guided by knowledge. Balance your heart and mind, and you will find the path to a life well-lived.', author: 'Bertrand Russell', category: 'LIFE' },
  { text: 'Do not take life too seriously. You will never get out of it alive. Laugh at yourself, find joy in the absurd, and remember that nobody has it all figured out.', author: 'Elbert Hubbard', category: 'LIFE' },
  { text: 'You only live once, but if you do it right, once is enough. Don\'t wait for permission to live the life you want. This is your one shot — make it count.', author: 'Mae West', category: 'LIFE' },
  { text: 'Life is about making an impact, not making an income. The legacy you leave behind is measured not by what you accumulated, but by how many lives you touched.', author: 'Kevin Kruse', category: 'LIFE' },
  { text: 'Every moment is a fresh beginning. No matter what happened yesterday, today is a new day with new possibilities. You can start over anytime you choose.', author: 'T.S. Eliot', category: 'LIFE' },
  // ── FUNNY (12) ──
  { text: 'I am so clever that sometimes I don\'t understand a single word of what I am saying. Intelligence is a burden, and I carry it with great difficulty.', author: 'Oscar Wilde', category: 'FUNNY' },
  { text: 'People say nothing is impossible, but I do nothing every day. I am living proof that doing nothing is not only possible but can be perfected with practice.', author: 'A. A. Milne', category: 'FUNNY' },
  { text: 'I\'m not arguing, I\'m just passionately explaining why I\'m correct. There is a fine line between an argument and an educational lecture, and I walk it gracefully.', author: 'Sohel Khan', category: 'FUNNY' },
  { text: 'If you think you are too small to make a difference, try sleeping with a mosquito. The smallest creatures can create the biggest annoyances, and so can you.', author: 'Dalai Lama', category: 'FUNNY' },
  { text: 'My fake plants died because I did not pretend to water them. Commitment issues extend even to my imaginary garden.', author: 'Mitch Hedberg', category: 'FUNNY' },
  { text: 'Behind every great man is a woman rolling her eyes. And behind every successful woman is herself, wondering why she puts up with all this nonsense.', author: 'Jim Carrey', category: 'FUNNY' },
  { text: 'The difference between stupidity and genius is that genius has its limits. Stupidity, on the other hand, is a renewable resource of infinite capacity.', author: 'Albert Einstein', category: 'FUNNY' },
  { text: 'I can resist everything except temptation. And snacks. And sleeping in. And buying things I don\'t need. Okay, maybe I can\'t resist much.', author: 'Oscar Wilde', category: 'FUNNY' },
  { text: 'Common sense is like deodorant. The people who need it most never use it. Walk through any public space and you will confirm this universal truth.', author: 'Sohel Khan', category: 'FUNNY' },
  { text: 'Never put off till tomorrow what may be done the day after tomorrow just as well. Procrastination is an art form, and I consider myself a master.', author: 'Mark Twain', category: 'FUNNY' },
  { text: 'I always wanted to be somebody, but now I realize I should have been more specific. Being "somebody" is a very vague career goal.', author: 'Lily Tomlin', category: 'FUNNY' },
  { text: 'Age is an issue of mind over matter. If you don\'t mind, it doesn\'t matter. I plan to be immature for as long as humanly possible.', author: 'Mark Twain', category: 'FUNNY' },
  // ── LEADERSHIP (12) ──
  { text: 'A leader is one who knows the way, goes the way, and shows the way. Leadership is not about giving orders — it is about setting an example worth following.', author: 'John C. Maxwell', category: 'LEADERSHIP' },
  { text: 'Leadership is not about being in charge. It is about taking care of those in your charge. A true leader serves the people, not the other way around.', author: 'Simon Sinek', category: 'LEADERSHIP' },
  { text: 'The function of leadership is to produce more leaders, not more followers. The mark of a great leader is how many leaders they create, not how many followers they gather.', author: 'Ralph Nader', category: 'LEADERSHIP' },
  { text: 'Do not follow where the path may lead. Go instead where there is no path and leave a trail. True leaders are pioneers who create new possibilities.', author: 'Ralph Waldo Emerson', category: 'LEADERSHIP' },
  { text: 'Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.', author: 'Jack Welch', category: 'LEADERSHIP' },
  { text: 'If your actions inspire others to dream more, learn more, do more and become more, you are a leader. Leadership is measured by impact, not title.', author: 'John Quincy Adams', category: 'LEADERSHIP' },
  { text: 'A good leader takes a little more than his share of the blame and a little less than his share of the credit. Humility is the hallmark of true leadership.', author: 'Arnold H. Glasow', category: 'LEADERSHIP' },
  { text: 'Leadership and learning are indispensable to each other. The moment a leader stops learning, they stop leading effectively.', author: 'John F. Kennedy', category: 'LEADERSHIP' },
  { text: 'Leaders are made, they are not born. They are made by hard effort, which is the price all of us must pay to achieve any goal that is worthwhile.', author: 'Vince Lombardi', category: 'LEADERSHIP' },
  { text: 'Innovation distinguishes between a leader and a follower. Leaders embrace change; followers resist it.', author: 'Steve Jobs', category: 'LEADERSHIP' },
  { text: 'A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others.', author: 'Douglas MacArthur', category: 'LEADERSHIP' },
  { text: 'The art of leadership is saying no, not yes. It is very easy to say yes. True leadership requires the wisdom to know when to say no.', author: 'Tony Blair', category: 'LEADERSHIP' },
  // ── EDUCATION (12) ──
  { text: 'Education is the most powerful weapon which you can use to change the world. No army can stop an idea whose time has come, and education plants those ideas.', author: 'Nelson Mandela', category: 'EDUCATION' },
  { text: 'The roots of education are bitter, but the fruit is sweet. The process of learning is often difficult and painful, but the rewards it brings are beyond measure.', author: 'Aristotle', category: 'EDUCATION' },
  { text: 'Education is not preparation for life; education is life itself. Learning doesn\'t stop when you leave school — it continues every single day you are alive.', author: 'John Dewey', category: 'EDUCATION' },
  { text: 'The beautiful thing about learning is that no one can take it away from you. Money can be stolen, possessions lost, but knowledge is yours forever.', author: 'B.B. King', category: 'EDUCATION' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever. Every day is an opportunity to learn something new.', author: 'Mahatma Gandhi', category: 'EDUCATION' },
  { text: 'Intelligence plus character — that is the goal of true education. Education that builds only the mind without building the heart creates clever devils, not wise humans.', author: 'Martin Luther King Jr.', category: 'EDUCATION' },
  { text: 'The mind is not a vessel to be filled, but a fire to be kindled. True education ignites curiosity, it doesn\'t just dump information.', author: 'Plutarch', category: 'EDUCATION' },
  { text: 'Learning never exhausts the mind. The more you learn, the more you realize how much there is still to discover.', author: 'Leonardo da Vinci', category: 'EDUCATION' },
  { text: 'Education is what remains after one has forgotten what one has learned in school. The habits of thinking, questioning, and persevering are the real gifts of education.', author: 'Albert Einstein', category: 'EDUCATION' },
  { text: 'Tell me and I forget. Teach me and I remember. Involve me and I learn. True education is not passive — it is active, engaged, and experiential.', author: 'Benjamin Franklin', category: 'EDUCATION' },
  { text: 'The more that you read, the more things you will know. The more that you learn, the more places you\'ll go.', author: 'Dr. Seuss', category: 'EDUCATION' },
  { text: 'Education is the passport to the future, for tomorrow belongs to those who prepare for it today. Invest in your mind.', author: 'Malcolm X', category: 'EDUCATION' },
  // ── SPIRITUALITY (12) ──
  { text: 'The only journey is the one within. External achievements mean nothing if you have not explored the depths of your own soul.', author: 'Rainer Maria Rilke', category: 'SPIRITUALITY' },
  { text: 'Peace comes from within. Do not seek it without. No amount of external change can bring inner peace if your mind is at war with itself.', author: 'Buddha', category: 'SPIRITUALITY' },
  { text: 'You are not a drop in the ocean. You are the entire ocean in a drop. The entire universe exists within you, waiting to be discovered.', author: 'Rumi', category: 'SPIRITUALITY' },
  { text: 'The wound is the place where the Light enters you. Your deepest pain can become your greatest source of strength and wisdom.', author: 'Rumi', category: 'SPIRITUALITY' },
  { text: 'Be the change that you wish to see in the world. If you want peace, be peaceful. If you want kindness, be kind.', author: 'Mahatma Gandhi', category: 'SPIRITUALITY' },
  { text: 'The best way to find yourself is to lose yourself in the service of others. When you help others, you discover your true purpose.', author: 'Mahatma Gandhi', category: 'SPIRITUALITY' },
  { text: 'What we think, we become. Your thoughts shape your reality more than any external circumstance ever could.', author: 'Buddha', category: 'SPIRITUALITY' },
  { text: 'The soul always knows what to do to heal itself. The challenge is to silence the mind. Trust your inner wisdom.', author: 'Sohel Khan', category: 'SPIRITUALITY' },
  { text: 'Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.', author: 'Rumi', category: 'SPIRITUALITY' },
  { text: 'Happiness is not something ready-made. It comes from your own actions. Peace is a practice, not a destination.', author: 'Dalai Lama', category: 'SPIRITUALITY' },
  { text: 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', author: 'Rumi', category: 'SPIRITUALITY' },
  { text: 'The meaning of life is to find your gift. The purpose of life is to give it away. Your unique talents are not for you alone.', author: 'Pablo Picasso', category: 'SPIRITUALITY' },
  // ── NATURE (12) ──
  { text: 'Look deep into nature, and then you will understand everything better. The wisdom of the universe is written in the patterns of the natural world.', author: 'Albert Einstein', category: 'NATURE' },
  { text: 'In every walk with nature one receives far more than he seeks. The forest gives you exactly what you need, even if you didn\'t know you needed it.', author: 'John Muir', category: 'NATURE' },
  { text: 'Nature does not hurry, yet everything is accomplished. A river cuts through rock not because of its power, but because of its persistence.', author: 'Lao Tzu', category: 'NATURE' },
  { text: 'The earth has music for those who listen. The wind, the birds, the rustling leaves — there is a symphony playing all around you.', author: 'William Shakespeare', category: 'NATURE' },
  { text: 'Adopt the pace of nature: her secret is patience. Trees take decades to grow. Flowers bloom when they are ready. Trust the timing of your life.', author: 'Ralph Waldo Emerson', category: 'NATURE' },
  { text: 'Heaven is under our feet as well as over our heads. You don\'t need to look up to find paradise — it is right here, beneath the soil and stone.', author: 'Henry David Thoreau', category: 'NATURE' },
  { text: 'The clearest way into the Universe is through a forest wilderness. When you are lost among the trees, you find yourself.', author: 'John Muir', category: 'NATURE' },
  { text: 'Study nature, love nature, stay close to nature. It will never fail you. Nature is the most reliable teacher, healer, and friend you will ever have.', author: 'Frank Lloyd Wright', category: 'NATURE' },
  { text: 'Nature is not a place to visit. It is home. We are not separate from nature — we are a part of it.', author: 'Gary Snyder', category: 'NATURE' },
  { text: 'To sit in the shade on a fine day and look upon verdure is the most perfect refreshment. Simple pleasures are the sweetest.', author: 'Jane Austen', category: 'NATURE' },
  { text: 'If you truly love nature, you will find beauty everywhere. Even in the cracks of the sidewalk, life finds a way.', author: 'Vincent Van Gogh', category: 'NATURE' },
  { text: 'The mountains are calling and I must go. There is a wildness in the human spirit that only nature can satisfy.', author: 'John Muir', category: 'NATURE' }
]
