export const categories = {
  MOTIVATION:         { label: 'Motivation',          emoji: '🚀' },
  SUCCESS:            { label: 'Success',             emoji: '🏆' },
  TECH:               { label: 'Tech',                emoji: '💻' },
  CRITICAL_THINKING:  { label: 'Critical Thinking',   emoji: '🧠' },
  HINDI:              { label: 'हिंदी विचार',         emoji: '🇮🇳' },
  URDU:               { label: 'اردو اقوال',          emoji: '🌙' },
  LOVE:               { label: 'Love',                emoji: '💕' },
  WISDOM:             { label: 'Wisdom',              emoji: '🦉' },
  LIFE:               { label: 'Life',                emoji: '🌟' },
  FUNNY:              { label: 'Funny',               emoji: '😂' },
  LIKED:              { label: 'Liked Quotes',        emoji: '❤️' }
}

export const gradients = {
  MOTIVATION:         ['#667EEA', '#764BA2'],
  SUCCESS:            ['#F093FB', '#F5576C'],
  TECH:               ['#4FACFE', '#00F2FE'],
  CRITICAL_THINKING:  ['#43E97B', '#38F9D7'],
  HINDI:              ['#FF9933', '#FF6B35'],
  URDU:               ['#2B6B4F', '#1A4731'],
  LOVE:               ['#FF6B6B', '#EE5A24'],
  WISDOM:             ['#8E44AD', '#2C3E50'],
  LIFE:               ['#00B4DB', '#0083B0'],
  FUNNY:              ['#F2994A', '#F2C94C'],
  LIKED:              ['#E91E63', '#9C27B0']
}

export const currentYear = new Date().getFullYear()

export const allQuotes = [
  // ── MOTIVATION (7) ──
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs', category: 'MOTIVATION' },
  { text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt', category: 'MOTIVATION' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius', category: 'MOTIVATION' },
  { text: 'Your time is limited, don\'t waste it living someone else\'s life.', author: 'Steve Jobs', category: 'MOTIVATION' },
  { text: 'Everything you\'ve ever wanted is on the other side of fear.', author: 'George Addair', category: 'MOTIVATION' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt', category: 'MOTIVATION' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill', category: 'MOTIVATION' },
  // ── SUCCESS (6) ──
  { text: 'Success is not the key to happiness. Happiness is the key to success.', author: 'Albert Schweitzer', category: 'SUCCESS' },
  { text: 'Don\'t be afraid to give up the good to go for the great.', author: 'John D. Rockefeller', category: 'SUCCESS' },
  { text: 'The secret of success is to do the common things uncommonly well.', author: 'John D. Rockefeller Jr.', category: 'SUCCESS' },
  { text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau', category: 'SUCCESS' },
  { text: 'Opportunities don\'t happen. You create them.', author: 'Chris Grosser', category: 'SUCCESS' },
  { text: 'The only place where success comes before work is in the dictionary.', author: 'Vidal Sassoon', category: 'SUCCESS' },
  // ── TECH (6) ──
  { text: 'The technology you use impresses no one. The experience you create with it is everything.', author: 'Sean Geraty', category: 'TECH' },
  { text: 'It\'s not that we use technology, we live technology.', author: 'Godfrey Reggio', category: 'TECH' },
  { text: 'Any sufficiently advanced technology is indistinguishable from magic.', author: 'Arthur C. Clarke', category: 'TECH' },
  { text: 'First we shape our tools, then our tools shape us.', author: 'Marshall McLuhan', category: 'TECH' },
  { text: 'Code is like humor. When you have to explain it, it\'s bad.', author: 'Cory House', category: 'TECH' },
  { text: 'The computer was born to solve problems that did not exist before.', author: 'Bill Gates', category: 'TECH' },
  // ── CRITICAL THINKING (6) ──
  { text: 'The unexamined life is not worth living.', author: 'Socrates', category: 'CRITICAL_THINKING' },
  { text: 'It is the mark of an educated mind to be able to entertain a thought without accepting it.', author: 'Aristotle', category: 'CRITICAL_THINKING' },
  { text: 'We cannot solve our problems with the same thinking we used when we created them.', author: 'Albert Einstein', category: 'CRITICAL_THINKING' },
  { text: 'Question everything. Learn something. Answer nothing.', author: 'Euripides', category: 'CRITICAL_THINKING' },
  { text: 'Thinking is the hardest work there is, which is probably the reason so few engage in it.', author: 'Henry Ford', category: 'CRITICAL_THINKING' },
  { text: 'Wise men speak because they have something to say; fools because they have to say something.', author: 'Plato', category: 'CRITICAL_THINKING' },
  // ── HINDI (25) ──
  { text: 'अपने लक्ष्य को इतना बड़ा बनाओ कि रास्ते छोटे लगें।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जिंदगी में दो चीजें कभी मत छोड़ो — एक उम्मीद और दूसरा हौसला।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'कामयाबी उन्हीं को मिलती है जो अपनी गलतियों से सीखते हैं।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'मंजिल उन्हीं को मिलती है जिनके सपनों में जान होती है, पंखों से कुछ नहीं होता हौसलों से उड़ान होती है।', author: 'डॉ. ए.पी.जे. अब्दुल कलाम', category: 'HINDI' },
  { text: 'जो लोग अपनी सोच को बदल सकते हैं, वही दुनिया को बदल सकते हैं।', author: 'स्वामी विवेकानंद', category: 'HINDI' },
  { text: 'सपने वो नहीं जो हम सोते वक्त देखते हैं, सपने वो हैं जो हमें सोने नहीं देते।', author: 'डॉ. ए.पी.जे. अब्दुल कलाम', category: 'HINDI' },
  { text: 'जिंदगी एक खेल है, इसे खेलना सीखो, हार या जीत किस्मत की बात है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'सफलता का कोई शॉर्टकट नहीं होता, मेहनत ही एकमात्र रास्ता है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'उठो, जागो और तब तक मत रुको जब तक लक्ष्य प्राप्त न हो जाए।', author: 'स्वामी विवेकानंद', category: 'HINDI' },
  { text: 'कठिनाइयों से भागो मत, उनका सामना करो, वही तुम्हें मजबूत बनाएंगी।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जो खुद पर विश्वास करते हैं, वही दुनिया जीतते हैं।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जीवन में जो कुछ भी बड़ा हासिल होता है, वो पहले सपने में आता है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'अकेले चलो, अगर कोई साथ नहीं देता। रास्ता खुद बन जाएगा।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'मेहनत इतनी खामोशी से करो कि सफलता शोर मचा दे।', author: 'डॉ. ए.पी.जे. अब्दुल कलाम', category: 'HINDI' },
  { text: 'जो हम सोचते हैं वो हम बन जाते हैं।', author: 'महात्मा गांधी', category: 'HINDI' },
  { text: 'मन के हारे हार है, मन के जीते जीत।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'जो वक्त का इंतजार करते हैं, वक्त उनका नहीं होता।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'हिम्मत वह नहीं जो गिरने से बचाए, हिम्मत वो है जो गिरने के बाद उठना सिखाए।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'बुरा जो देखन मैं चला, बुरा न मिलिया कोय। जो मन खोजा आपना, तो मुझसे बुरा न कोय।', author: 'संत कबीर दास', category: 'HINDI' },
  { text: 'चलती चक्की देख के, दिया कबीरा रोय। दो पाटन के बीच में, साबुत बचा न कोय।', author: 'संत कबीर दास', category: 'HINDI' },
  { text: 'दुख में सुमिरन सब करें, सुख में करे न कोय। जो सुख में सुमिरन करे, तो दुख काहे को होय।', author: 'संत कबीर दास', category: 'HINDI' },
  { text: 'जीवन एक उपहार है, इसे स्वीकार करो।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'खुश रहना सबसे बड़ी सफलता है।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'सादा जीवन उच्च विचार।', author: 'Sohel Khan', category: 'HINDI' },
  { text: 'सच्चा सुख संतोष में है।', author: 'Sohel Khan', category: 'HINDI' },
  // ── URDU (25) ──
  { text: 'خدا اس کی مدد کرتا ہے جو خود اپنی مدد کرتا ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'محنت کا کوئی متبادل نہیں ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'جہاں چاہ وہاں راہ۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'اپنے خوابوں کو اتنا بڑا بناؤ کہ راستے چھوٹے لگیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'زندگی میں دو چیزیں کبھی مت چھوڑو — ایک امید اور دوسرا حوصلہ۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'کامیابی انہیں کو ملتی ہے جو اپنی غلطیوں سے سیکھتے ہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'منزل انہیں کو ملتی ہے جن کے خوابوں میں جان ہوتی ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'جو لوگ اپنی سوچ کو بدل سکتے ہیں، وہی دنیا کو بدل سکتے ہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'خواب وہ نہیں جو ہم سوتے وقت دیکھتے ہیں، خواب وہ ہیں جو ہمیں سونے نہیں دیتے۔', author: 'ڈاکٹر اے پی جے عبدالکلام', category: 'URDU' },
  { text: 'زندگی ایک کھیل ہے، اسے کھیلنا سیکھو، ہار یا جیت قسمت کی بات ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'اٹھو، جاگو اور تب تک مت رکو جب تک منزل حاصل نہ ہو جائے۔', author: 'سوامی ویویکانند', category: 'URDU' },
  { text: 'مشکلات سے بھاگو مت، ان کا سامنا کرو، وہی تمہیں مضبوط بنائیں گی۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'جو خود پر یقین رکھتے ہیں، وہی دنیا جیتتے ہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'اگر آپ آسمان کی بلندی کو چھونا چاہتے ہیں، تو زمین پر پاؤں رکھ کر رہنا سیکھیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'تعلیم سب سے طاقتور ہتھیار ہے جس سے آپ دنیا بدل سکتے ہیں۔', author: 'نیلسن منڈیلا', category: 'URDU' },
  { text: 'محنت اتنی خاموشی سے کرو کہ کامیابی شور مچا دے۔', author: 'ڈاکٹر اے پی جے عبدالکلام', category: 'URDU' },
  { text: 'زندگی چھوٹی ہے، اسے بڑے کاموں کے لیے استعمال کرو۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'ہار تب نہیں ہوتی جب آپ گرتے ہیں، ہار تب ہوتی ہے جب آپ اٹھتے نہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'خود پر یقین رکھنے والے لوگ ہی تاریخ بناتے ہیں۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'خوش رہنا سب سے بڑی کامیابی ہے۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'وقت کسی کے لیے نہیں رکتا، اس لیے ابھی شروع کرو۔', author: 'Sohel Khan', category: 'URDU' },
  { text: 'عشق نے غالبؔ نکما کر دیا، ورنہ ہم بھی آدمی تھے کام کے۔', author: 'مرزا غالب', category: 'URDU' },
  { text: 'ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے، بہت نکلے مرے ارمان لیکن پھر بھی کم نکلے۔', author: 'مرزا غالب', category: 'URDU' },
  { text: 'دردِ دل کے واسطے پیدا کیا انسان کو، ورنہ اطاعت کے لیے کچھ کم نہ تھے کروبیاں۔', author: 'اقبال', category: 'URDU' },
  { text: 'خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے، خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے۔', author: 'علامہ اقبال', category: 'URDU' },
  // ── LOVE (12) ──
  { text: 'Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.', author: 'Sohel Khan', category: 'LOVE' },
  { text: 'The best thing to hold onto in life is each other.', author: 'Audrey Hepburn', category: 'LOVE' },
  { text: 'Where there is love there is life.', author: 'Mahatma Gandhi', category: 'LOVE' },
  { text: 'Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.', author: 'Maya Angelou', category: 'LOVE' },
  { text: 'We are most alive when we are in love.', author: 'John Updike', category: 'LOVE' },
  { text: 'To love and be loved is to feel the sun from both sides.', author: 'David Viscott', category: 'LOVE' },
  { text: 'Love is composed of a single soul inhabiting two bodies.', author: 'Aristotle', category: 'LOVE' },
  { text: 'The greatest happiness of life is the conviction that we are loved.', author: 'Victor Hugo', category: 'LOVE' },
  { text: 'Love is when the other person\'s happiness is more important than your own.', author: 'H. Jackson Brown Jr.', category: 'LOVE' },
  { text: 'In the end, the love you take is equal to the love you make.', author: 'Paul McCartney', category: 'LOVE' },
  { text: 'Love all, trust a few, do wrong to none.', author: 'William Shakespeare', category: 'LOVE' },
  { text: 'A loving heart is the truest wisdom.', author: 'Charles Dickens', category: 'LOVE' },
  // ── WISDOM (12) ──
  { text: 'The only true wisdom is in knowing you know nothing.', author: 'Socrates', category: 'WISDOM' },
  { text: 'Knowledge speaks, but wisdom listens.', author: 'Jimi Hendrix', category: 'WISDOM' },
  { text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey', category: 'WISDOM' },
  { text: 'The fool doth think he is wise, but the wise man knows himself to be a fool.', author: 'William Shakespeare', category: 'WISDOM' },
  { text: 'Wisdom begins in wonder.', author: 'Socrates', category: 'WISDOM' },
  { text: 'Do not seek to follow in the footsteps of the wise. Seek what they sought.', author: 'Matsuo Basho', category: 'WISDOM' },
  { text: 'By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.', author: 'Confucius', category: 'WISDOM' },
  { text: 'The simple things are also the most extraordinary things, and only the wise can see them.', author: 'Paulo Coelho', category: 'WISDOM' },
  { text: 'Honesty is the first chapter in the book of wisdom.', author: 'Thomas Jefferson', category: 'WISDOM' },
  { text: 'It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.', author: 'Maurice Switzer', category: 'WISDOM' },
  { text: 'The invariable mark of wisdom is to see the miraculous in the common.', author: 'Ralph Waldo Emerson', category: 'WISDOM' },
  { text: 'Silence is the sleep that nourishes wisdom.', author: 'Francis Bacon', category: 'WISDOM' },
  // ── LIFE (12) ──
  { text: 'Life is what happens when you\'re busy making other plans.', author: 'John Lennon', category: 'LIFE' },
  { text: 'The purpose of our lives is to be happy.', author: 'Dalai Lama', category: 'LIFE' },
  { text: 'Get busy living or get busy dying.', author: 'Stephen King', category: 'LIFE' },
  { text: 'You only live once, but if you do it right, once is enough.', author: 'Mae West', category: 'LIFE' },
  { text: 'Many of life\'s failures are people who did not realize how close they were to success when they gave up.', author: 'Thomas A. Edison', category: 'LIFE' },
  { text: 'If you want to live a happy life, tie it to a goal, not to people or things.', author: 'Albert Einstein', category: 'LIFE' },
  { text: 'The whole secret of a successful life is to find out what is one\'s destiny to do, and then do it.', author: 'Henry Ford', category: 'LIFE' },
  { text: 'In three words I can sum up everything I\'ve learned about life: it goes on.', author: 'Robert Frost', category: 'LIFE' },
  { text: 'Life is really simple, but we insist on making it complicated.', author: 'Confucius', category: 'LIFE' },
  { text: 'The biggest adventure you can take is to live the life of your dreams.', author: 'Oprah Winfrey', category: 'LIFE' },
  { text: 'Life is either a daring adventure or nothing at all.', author: 'Helen Keller', category: 'LIFE' },
  { text: 'Do not take life too seriously. You will never get out of it alive.', author: 'Elbert Hubbard', category: 'LIFE' },
  // ── FUNNY (12) ──
  { text: 'I am so clever that sometimes I don\'t understand a single word of what I am saying.', author: 'Oscar Wilde', category: 'FUNNY' },
  { text: 'People say nothing is impossible, but I do nothing every day.', author: 'A. A. Milne', category: 'FUNNY' },
  { text: 'The only thing that interferes with my learning is my education.', author: 'Albert Einstein', category: 'FUNNY' },
  { text: 'I\'m not arguing, I\'m just explaining why I\'m right.', author: 'Sohel Khan', category: 'FUNNY' },
  { text: 'I always wanted to be somebody, but now I realize I should have been more specific.', author: 'Lily Tomlin', category: 'FUNNY' },
  { text: 'If you think you are too small to make a difference, try sleeping with a mosquito.', author: 'Dalai Lama', category: 'FUNNY' },
  { text: 'My fake plants died because I did not pretend to water them.', author: 'Mitch Hedberg', category: 'FUNNY' },
  { text: 'Behind every great man is a woman rolling her eyes.', author: 'Jim Carrey', category: 'FUNNY' },
  { text: 'The difference between stupidity and genius is that genius has its limits.', author: 'Albert Einstein', category: 'FUNNY' },
  { text: 'I can resist everything except temptation.', author: 'Oscar Wilde', category: 'FUNNY' },
  { text: 'Age is an issue of mind over matter. If you don\'t mind, it doesn\'t matter.', author: 'Mark Twain', category: 'FUNNY' },
  { text: 'Never put off till tomorrow what may be done the day after tomorrow just as well.', author: 'Mark Twain', category: 'FUNNY' }
]
