export const categories = {
  MOTIVATION:         { label: 'Motivation',          emoji: '🚀' },
  SUCCESS:            { label: 'Success',             emoji: '🏆' },
  TECH:               { label: 'Tech',                emoji: '💻' },
  CRITICAL_THINKING:  { label: 'Critical Thinking',   emoji: '🧠' },
  HINDI:              { label: 'हिंदी विचार',         emoji: '🕉️' },
  URDU:               { label: 'اردو اقوال',          emoji: '🌙' },
  LIKED:              { label: 'Liked Quotes',        emoji: '❤️' }
}

export const gradients = {
  MOTIVATION:         ['#667EEA', '#764BA2'],
  SUCCESS:            ['#F093FB', '#F5576C'],
  TECH:               ['#4FACFE', '#00F2FE'],
  CRITICAL_THINKING:  ['#43E97B', '#38F9D7'],
  HINDI:              ['#FF9933', '#FF6B35'],
  URDU:               ['#2B6B4F', '#1A4731'],
  LIKED:              ['#E91E63', '#9C27B0']
}

export const currentYear = new Date().getFullYear()

export const allQuotes = [
  // ── MOTIVATION (7) ──
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs', category: 'MOTIVATION' },
  { text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt', category: 'MOTIVATION' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius', category: 'MOTIVATION' },
  { text: 'Your time is limited, don\'t waste it living someone else\'s life.', author: 'Steve Jobs', category: 'MOTIVATION' },
  { text: 'Everything you\'ve ever wanted is on the other side of fear.', author: 'George Addair', category: 'MOTIVATION' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt', category: 'MOTIVATION' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill', category: 'MOTIVATION' },
  // ── SUCCESS (6) ──
  { text: 'Success is not the key to happiness. Happiness is the key to success.', author: 'Albert Schweitzer', category: 'SUCCESS' },
  { text: 'Don\'t be afraid to give up the good to go for the great.', author: 'John D. Rockefeller', category: 'SUCCESS' },
  { text: 'The secret of success is to do the common things uncommonly well.', author: 'John D. Rockefeller Jr.', category: 'SUCCESS' },
  { text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau', category: 'SUCCESS' },
  { text: 'Opportunities don\'t happen. You create them.', author: 'Chris Grosser', category: 'SUCCESS' },
  { text: 'The only place where success comes before work is in the dictionary.', author: 'Vidal Sassoon', category: 'SUCCESS' },
  // ── TECH (6) ──
  { text: 'The technology you use impresses no one. The experience you create with it is everything.', author: 'Sean Geraty', category: 'TECH' },
  { text: 'It\'s not that we use technology, we live technology.', author: 'Godfrey Reggio', category: 'TECH' },
  { text: 'Any sufficiently advanced technology is indistinguishable from magic.', author: 'Arthur C. Clarke', category: 'TECH' },
  { text: 'First we shape our tools, then our tools shape us.', author: 'Marshall McLuhan', category: 'TECH' },
  { text: 'Code is like humor. When you have to explain it, it\'s bad.', author: 'Cory House', category: 'TECH' },
  { text: 'The computer was born to solve problems that did not exist before.', author: 'Bill Gates', category: 'TECH' },
  // ── CRITICAL THINKING (6) ──
  { text: 'The unexamined life is not worth living.', author: 'Socrates', category: 'CRITICAL_THINKING' },
  { text: 'It is the mark of an educated mind to be able to entertain a thought without accepting it.', author: 'Aristotle', category: 'CRITICAL_THINKING' },
  { text: 'We cannot solve our problems with the same thinking we used when we created them.', author: 'Albert Einstein', category: 'CRITICAL_THINKING' },
  { text: 'Question everything. Learn something. Answer nothing.', author: 'Euripides', category: 'CRITICAL_THINKING' },
  { text: 'Thinking is the hardest work there is, which is probably the reason so few engage in it.', author: 'Henry Ford', category: 'CRITICAL_THINKING' },
  { text: 'Wise men speak because they have something to say; fools because they have to say something.', author: 'Plato', category: 'CRITICAL_THINKING' },
  // ── HINDI (109) ──
  { text: 'अपने लक्ष्य को इतना बड़ा बनाओ कि रास्ते छोटे लगें।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जिंदगी में दो चीजें कभी मत छोड़ो — एक उम्मीद और दूसरा हौसला।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'कामयाबी उन्हीं को मिलती है जो अपनी गलतियों से सीखते हैं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'मंजिल उन्हीं को मिलती है जिनके सपनों में जान होती है, पंखों से कुछ नहीं होता हौसलों से उड़ान होती है।', author: 'डॉ. ए.पी.जे. अब्दुल कलाम', category: 'HINDI' },
  { text: 'जो लोग अपनी सोच को बदल सकते हैं, वही दुनिया को बदल सकते हैं।', author: 'स्वामी विवेकानंद', category: 'HINDI' },
  { text: 'सपने वो नहीं जो हम सोते वक्त देखते हैं, सपने वो हैं जो हमें सोने नहीं देते।', author: 'डॉ. ए.पी.जे. अब्दुल कलाम', category: 'HINDI' },
  { text: 'जिंदगी एक खेल है, इसे खेलना सीखो, हार या जीत किस्मत की बात है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सफलता का कोई शॉर्टकट नहीं होता, मेहनत ही एकमात्र रास्ता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'उठो, जागो और तब तक मत रुको जब तक लक्ष्य प्राप्त न हो जाए।', author: 'स्वामी विवेकानंद', category: 'HINDI' },
  { text: 'कठिनाइयों से भागो मत, उनका सामना करो, वही तुम्हें मजबूत बनाएंगी।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो खुद पर विश्वास करते हैं, वही दुनिया जीतते हैं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अगर आप आसमान की ऊंचाई को छूना चाहते हैं, तो जमीन पर पैर रखकर रहना सीखें।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जीवन में जो कुछ भी बड़ा हासिल होता है, वो पहले सपने में आता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अकेले चलो, अगर कोई साथ नहीं देता। रास्ता खुद बन जाएगा।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'शिक्षा सबसे शक्तिशाली हथियार है जिससे आप दुनिया बदल सकते हैं।', author: 'नेल्सन मंडेला', category: 'HINDI' },
  { text: 'मेहनत इतनी खामोशी से करो कि सफलता शोर मचा दे।', author: 'डॉ. ए.पी.जे. अब्दुल कलाम', category: 'HINDI' },
  { text: 'जिंदगी छोटी है, इसे बड़े कामों के लिए इस्तेमाल करो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'हार तब नहीं होती जब आप गिरते हैं, हार तब होती है जब आप उठते नहीं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अगर आप कुछ अलग करना चाहते हैं तो भीड़ से अलग होना पड़ेगा।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'खुद पर यकीन रखने वाले लोग ही इतिहास बनाते हैं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'बड़ा सोचो, बड़ा करो, बड़ा बनो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अपनी तुलना सिर्फ अपने कल से करो, दूसरों से नहीं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो हम सोचते हैं वो हम बन जाते हैं।', author: 'महात्मा गांधी', category: 'HINDI' },
  { text: 'हर दिन एक नया अवसर है, बस उसे पहचानने की जरूरत है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सफर खूबसूरत है मंजिल से भी, बस चलते रहने का जुनून होना चाहिए।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो जोखिम उठाते हैं, वही इतिहास रचते हैं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'हर असफलता एक नई सीख है, उसे गले लगाओ और आगे बढ़ो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सपने देखना छोड़ो मत, क्योंकि सपनों के बिना जिंदगी बेरंग है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'मेहनत का कोई विकल्प नहीं है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जहां चाह है वहां राह है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'कर भला तो हो भला, इससे बड़ा कोई कर्म नहीं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'इंसान की कीमत उसके कर्मों से होती है, शब्दों से नहीं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जीत उसी की होती है जो समय के साथ बदलना सीखता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सोने वालों से नहीं, जागने वालों से दुनिया आगे बढ़ती है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो अपनी गलती मान लेता है, वही असली बहादुर है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'खुश रहना सबसे बड़ी सफलता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'समय किसी के लिए नहीं रुकता, इसलिए अभी शुरू करो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'किताबें इंसान की सबसे अच्छी दोस्त होती हैं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'गिरते हैं शहसवार ही मैदान-ए-जंग में, वो तिफ्ल क्या गिरे जो घुटनों के बल चले।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अपने अंदर के डर को खत्म करो, बाहर का डर खुद-ब-खुद खत्म हो जाएगा।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'मन के हारे हार है, मन के जीते जीत।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अगर सूर्य को भी जलना पड़ता है, तो आपको भी मेहनत करनी पड़ेगी।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो वक्त का इंतजार करते हैं, वक्त उनका नहीं होता।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'हिम्मत वह नहीं जो गिरने से बचाए, हिम्मत वो है जो गिरने के बाद उठना सिखाए।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सीखने की कोई उम्र नहीं होती, हर दिन कुछ नया सीखो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'बुरा जो देखन मैं चला, बुरा न मिलिया कोय। जो मन खोजा आपना, तो मुझसे बुरा न कोय।', author: 'संत कबीर दास', category: 'HINDI' },
  { text: 'चलती चक्की देख के, दिया कबीरा रोय। दो पाटन के बीच में, साबुत बचा न कोय।', author: 'संत कबीर दास', category: 'HINDI' },
  { text: 'दुख में सुमिरन सब करें, सुख में करे न कोय। जो सुख में सुमिरन करे, तो दुख काहे को होय।', author: 'संत कबीर दास', category: 'HINDI' },
  { text: 'जो सत्य बोलता है, वह अपने आप को कभी अकेला नहीं पाता।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जिंदगी में परेशानियां आती हैं, लेकिन उनसे लड़ना सीखो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'कभी-कभी हार भी जरूरी है, क्योंकि हार से ही जीत की कीमत पता चलती है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'हार मत मानो, क्योंकि असंभव शब्द सिर्फ एक राय है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो व्यक्ति हर परिस्थिति में खुश रहता है, वही सबसे अमीर है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'आपकी सोच ही आपकी पहचान बनाती है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'खुशी बांटने से बढ़ती है, छुपाने से नहीं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो आज कर सकते हो उसे कल पर मत टालो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अपनी कमियों को अपनी ताकत बनाओ।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'ईश्वर उसी की मदद करता है जो खुद अपनी मदद करता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सादा जीवन उच्च विचार।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'कर्म ही पूजा है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो बीत गया सो बीत गया, अब आगे बढ़ो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'समय बर्बाद मत करो, क्योंकि यही जिंदगी है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'बिना संघर्ष के कुछ भी हासिल नहीं होता।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'आपका आज आपके कल से बेहतर हो, यही सच्ची तरक्की है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'दूसरों की मदद करने से बड़ा कोई पुण्य नहीं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो मिला है उस पर शुक्र करो, जो नहीं मिला उसकी शिकायत मत करो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'दुनिया का सबसे बड़ा साहस अपनी कमजोरी स्वीकार करना है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सपनों को कभी सीमित मत करो, सीमाओं को सपना बनाओ।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'आप जितना मेहनत करोगे, उतनी ही बड़ी सफलता मिलेगी।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'मुश्किलें इसलिए आती हैं ताकि आप और मजबूत बनो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जब तक जीना, तब तक सीखना।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'खुद को पहचानो, यही सबसे बड़ी शिक्षा है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'चिंता मत करो, भगवान सब अच्छा करेगा।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अच्छे कर्म कभी व्यर्थ नहीं जाते।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जीवन का असली आनंद दूसरों को खुशी देने में है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अगर हिम्मत हो तो रास्ते खुद बन जाते हैं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'नकारात्मक सोच को छोड़ो, सकारात्मक बनो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जीवन का हर पल कीमती है, इसे व्यर्थ मत जाने दो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'बड़े सपने देखो और उन्हें पूरा करने के लिए दिन-रात मेहनत करो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सच्चाई का रास्ता मुश्किल जरूर है, लेकिन असंभव नहीं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'हर सुबह एक नई उम्मीद लेकर आती है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो व्यक्ति खुद को हरा देता है, वह दुनिया को हरा सकता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'मेहनत का फल मीठा होता है, देर से ही सही।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'दोस्ती सबसे बड़ा रिश्ता है, इसे निभाना सीखो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो दूसरों की तारीफ करता है, वह खुद तारीफ के काबिल बनता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जीवन में लक्ष्य होना जरूरी है, बिना लक्ष्य के जीवन दिशाहीन है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'स्वास्थ्य ही सबसे बड़ा धन है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'परिश्रम का कोई तोड़ नहीं है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जीवन एक उपहार है, इसे स्वीकार करो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'माफ करना सबसे बड़ी ताकत है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'आज का काम कल पर मत छोड़ो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अपमान से बड़ा कोई दुख नहीं और सम्मान से बड़ा कोई सुख नहीं।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'क्रोध सबसे बड़ा शत्रु है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'बोलने से पहले सोचो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'इंसानियत सबसे बड़ा धर्म है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जहां प्रेम है, वहां ईश्वर है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'संगत का असर इंसान पर जरूर पड़ता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अनुभव सबसे बड़ा गुरु है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जो देता है वही पाता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'अच्छाई का रास्ता हमेशा खुला रहता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सब्र का फल मीठा होता है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'ज्ञान ही शक्ति है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'दुनिया में कुछ भी असंभव नहीं है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'छोटी-छोटी खुशियों का आनंद लो।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'जीवन सरल है, इसे जटिल मत बनाओ।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सबसे बड़ी जीत खुद पर जीत है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'हर इंसान में कोई न कोई खूबी होती है।', author: 'अज्ञात', category: 'HINDI' },
  { text: 'सच्चा सुख संतोष में है।', author: 'अज्ञात', category: 'HINDI' },
  // ── URDU (105) ──
  { text: 'خدا اس کی مدد کرتا ہے جو خود اپنی مدد کرتا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'محنت کا کوئی متبادل نہیں ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جہاں چاہ وہاں راہ۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اپنے خوابوں کو اتنا بڑا بناؤ کہ راستے چھوٹے لگیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'زندگی میں دو چیزیں کبھی مت چھوڑو — ایک امید اور دوسرا حوصلہ۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'کامیابی انہیں کو ملتی ہے جو اپنی غلطیوں سے سیکھتے ہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'منزل انہیں کو ملتی ہے جن کے خوابوں میں جان ہوتی ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو لوگ اپنی سوچ کو بدل سکتے ہیں، وہی دنیا کو بدل سکتے ہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'خواب وہ نہیں جو ہم سوتے وقت دیکھتے ہیں، خواب وہ ہیں جو ہمیں سونے نہیں دیتے۔', author: 'ڈاکٹر اے پی جے عبدالکلام', category: 'URDU' },
  { text: 'زندگی ایک کھیل ہے، اسے کھیلنا سیکھو، ہار یا جیت قسمت کی بات ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'کامیابی کا کوئی شارٹ کٹ نہیں ہوتا، محنت ہی واحد راستہ ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اٹھو، جاگو اور تب تک مت رکو جب تک منزل حاصل نہ ہو جائے۔', author: 'سوامی ویویکانند', category: 'URDU' },
  { text: 'مشکلات سے بھاگو مت، ان کا سامنا کرو، وہی تمہیں مضبوط بنائیں گی۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو خود پر یقین رکھتے ہیں، وہی دنیا جیتتے ہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اگر آپ آسمان کی بلندی کو چھونا چاہتے ہیں، تو زمین پر پاؤں رکھ کر رہنا سیکھیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'زندگی میں جو کچھ بھی بڑا حاصل ہوتا ہے، وہ پہلے خواب میں آتا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اکیلے چلو، اگر کوئی ساتھ نہیں دیتا۔ راستہ خود بن جائے گا۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'تعلیم سب سے طاقتور ہتھیار ہے جس سے آپ دنیا بدل سکتے ہیں۔', author: 'نیلسن منڈیلا', category: 'URDU' },
  { text: 'محنت اتنی خاموشی سے کرو کہ کامیابی شور مچا دے۔', author: 'ڈاکٹر اے پی جے عبدالکلام', category: 'URDU' },
  { text: 'زندگی چھوٹی ہے، اسے بڑے کاموں کے لیے استعمال کرو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'ہار تب نہیں ہوتی جب آپ گرتے ہیں، ہار تب ہوتی ہے جب آپ اٹھتے نہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اگر آپ کچھ الگ کرنا چاہتے ہیں تو بھیڑ سے الگ ہونا پڑے گا۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'خود پر یقین رکھنے والے لوگ ہی تاریخ بناتے ہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'بڑا سوچو، بڑا کرو، بڑا بنو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اپنا موازنہ صرف اپنے کل سے کرو، دوسروں سے نہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو ہم سوچتے ہیں وہ ہم بن جاتے ہیں۔', author: 'مہاتما گاندھی', category: 'URDU' },
  { text: 'یقین کرو کہ تم کر سکتے ہو اور تم آدھی منزل پار کر لو گے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'ہر دن ایک نیا موقع ہے، بس اسے پہچاننے کی ضرورت ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'سفر خوبصورت ہے منزل سے بھی، بس چلتے رہنے کا جنون ہونا چاہیے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو خطرہ اٹھاتے ہیں، وہی تاریخ رقم کرتے ہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'ہر ناکامی ایک نیا سبق ہے، اسے گلے لگاؤ اور آگے بڑھو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'خواب دیکھنا چھوڑو مت، کیونکہ خوابوں کے بغیر زندگی بے رنگ ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جہاں چاہ ہے وہاں راہ ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'انسان کی قیمت اس کے اعمال سے ہوتی ہے، الفاظ سے نہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جیت اسی کی ہوتی ہے جو وقت کے ساتھ بدلنا سیکھتا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'سونے والوں سے نہیں، جاگنے والوں سے دنیا آگے بڑھتی ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو اپنی غلطی مان لیتا ہے، وہی اصلی بہادر ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'خوش رہنا سب سے بڑی کامیابی ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'وقت کسی کے لیے نہیں رکتا، اس لیے ابھی شروع کرو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'کتابیں انسان کی سب سے اچھی دوست ہوتی ہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اپنے اندر کے ڈر کو ختم کرو، باہر کا ڈر خود بخود ختم ہو جائے گا۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'من کے ہارے ہار ہے، من کے جیتے جیت۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اگر سورج کو بھی جلنا پڑتا ہے، تو آپ کو بھی محنت کرنی پڑے گی۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو وقت کا انتظار کرتے ہیں، وقت ان کا نہیں ہوتا۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'ہمت وہ نہیں جو گرنے سے بچائے، ہمت وہ ہے جو گرنے کے بعد اٹھنا سکھائے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'سیکھنے کی کوئی عمر نہیں ہوتی، ہر دن کچھ نیا سیکھو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'زندگی میں مشکلات آتی ہیں، لیکن ان سے لڑنا سیکھو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'کبھی کبھی ہار بھی ضروری ہے، کیونکہ ہار سے ہی جیت کی قیمت پتہ چلتی ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'ہار مت مانو، کیونکہ ناممکن لفظ صرف ایک رائے ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو شخص ہر حالت میں خوش رہتا ہے، وہی سب سے امیر ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'آپ کی سوچ ہی آپ کی پہچان بناتی ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'خوشی بانٹنے سے بڑھتی ہے، چھپانے سے نہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو آج کر سکتے ہو اسے کل پر مت ٹالو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اپنی کمزوریوں کو اپنی طاقت بناؤ۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'سادہ زندگی اعلیٰ خیال۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'عمل ہی عبادت ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو گزر گیا سو گزر گیا، اب آگے بڑھو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'وقت ضائع مت کرو، کیونکہ یہی زندگی ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'بغیر جدوجہد کے کچھ بھی حاصل نہیں ہوتا۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'آپ کا آج آپ کے کل سے بہتر ہو، یہی سچی ترقی ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'دوسروں کی مدد کرنے سے بڑا کوئی ثواب نہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو ملا ہے اس پر شکر کرو، جو نہیں ملا اس کی شکایت مت کرو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'دنیا کا سب سے بڑا حوصلہ اپنی کمزوری قبول کرنا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'خوابوں کو کبھی محدود مت کرو، حدود کو خواب بناؤ۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'آپ جتنی محنت کرو گے، اتنی ہی بڑی کامیابی ملے گی۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'مشکلیں اس لیے آتی ہیں تاکہ آپ اور مضبوط بنو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جب تک جینا، تب تک سیکھنا۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'خود کو پہچانو، یہی سب سے بڑی تعلیم ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اچھے اعمال کبھی رائیگاں نہیں جاتے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'زندگی کا اصل لطف دوسروں کو خوشی دینے میں ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اگر ہمت ہو تو راستے خود بن جاتے ہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'منفی سوچ کو چھوڑو، مثبت بنو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'زندگی کا ہر لمحہ قیمتی ہے، اسے رائیگاں مت جانے دو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'بڑے خواب دیکھو اور انہیں پورا کرنے کے لیے دن رات محنت کرو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'سچائی کا راستہ مشکل ضرور ہے، لیکن ناممکن نہیں۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'ہر صبح ایک نئی امید لے کر آتی ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو شخص خود کو ہرا دیتا ہے، وہ دنیا کو ہرا سکتا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'محنت کا پھل میٹھا ہوتا ہے، دیر سے ہی سہی۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'دوستی سب سے بڑا رشتہ ہے، اسے نبھانا سیکھو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو دوسروں کی تعریف کرتا ہے، وہ خود تعریف کے قابل بنتا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'زندگی میں مقصد ہونا ضروری ہے، بغیر مقصد کے زندگی بے سمت ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'صحت ہی سب سے بڑا مال ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'محنت کا کوئی توڑ نہیں ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'زندگی ایک تحفہ ہے، اسے قبول کرو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'معاف کرنا سب سے بڑی طاقت ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'آج کا کام کل پر مت چھوڑو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'غصہ سب سے بڑا دشمن ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'بولنے سے پہلے سوچو۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'انسانیت سب سے بڑا مذہب ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جہاں محبت ہے، وہاں خدا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'صحبت کا اثر انسان پر ضرور پڑتا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'تجربہ سب سے بڑا استاد ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'جو دیتا ہے وہی پاتا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'اچھائی کا راستہ ہمیشہ کھلا رہتا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'صبر کا پھل میٹھا ہوتا ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'علم ہی طاقت ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'دنیا میں کچھ بھی ناممکن نہیں ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'چھوٹی چھوٹی خوشیوں کا لطف اٹھاؤ۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'زندگی آسان ہے، اسے پیچیدہ مت بناؤ۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'سب سے بڑی جیت خود پر جیت ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'ہر انسان میں کوئی نہ کوئی خوبی ہوتی ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'سچی خوشی قناعت میں ہے۔', author: 'نامعلوم', category: 'URDU' },
  { text: 'عشق نے غالبؔ نکما کر دیا، ورنہ ہم بھی آدمی تھے کام کے۔', author: 'مرزا غالب', category: 'URDU' },
  { text: 'ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے، بہت نکلے مرے ارمان لیکن پھر بھی کم نکلے۔', author: 'مرزا غالب', category: 'URDU' },
  { text: 'دردِ دل کے واسطے پیدا کیا انسان کو، ورنہ اطاعت کے لیے کچھ کم نہ تھے کروبیاں۔', author: 'اقبال', category: 'URDU' },
  { text: 'خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے، خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے۔', author: 'علامہ اقبال', category: 'URDU' }
]
